### ISSUE TITLE
remote connection

### ISSUE THREAD

**Issue by pcmodder2001** [Thefrank/jellyfin-server-freebsd#33]
Hiya, 

not sure if this is the right place however...

got everything set up and working (i think) but im trying to accsess the jellyfin server remotley but im getting no where. ive port forwared on my router but still cant connect. 

is there something im missing?

**Comment by badrpc** [comment]
It is very hard to give any practical advises (in particular because you don't say how exactly it is not working for you). But indeed it is unlikely that the problem is specific to FreeBSD port of Jellyfin. I configured it behind the reverse proxy following https://jellyfin.org/docs/general/networking/nginx/ (Nginx from a subdomain variant) and it works as expected. I think I also tried enabling HTTPS in Jellyfin and exposing it directly but enabling HTTPS broke DLNA streaming in the LAN (which turned out to be a known issue) so I settled on Jellyfin behind Nginx.

**Comment by Thefrank** [comment]
Your best (easiest?) way would be to use a reverse proxy as @badrpc suggested. I am a fan of NGINX or HAProxy for that.

**Comment by rucko24** [comment]
**Hi,**

https://jellyfin.org/docs/general/networking/nginx/

I tried another approach for real and it went very well indeed. 

I have a reverse proxy, installed on a freeBSD jail as well as jellyfin, and without any problem I can access remotely. 

My steps I put them here, only they are in Spanish.
