### ISSUE TITLE
Build jellyfin-ffmpeg

### ISSUE THREAD

**Issue by SavageCore** [Thefrank/jellyfin-server-freebsd#37]
Hello

It would be great if you could build and bundle `jellyfin-ffmpeg` >= `5.0.1-5` for https://github.com/ConfusedPolarBear/intro-skipper

Trying to run detection currently logs:

```
[2023-01-20 00:00:00.000 +00:00] [ERR] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: ffmpeg with chromaprint is not installed on this system - episodes will not be analyzed. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade it to the latest version of 10.8.0.
   at ConfusedPolarBear.Plugin.IntroSkipper.QueueManager.EnqueueAllEpisodes()
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by Thefrank** [comment]
If it ONLY needs `chromaprint` and nothing special that jellyfin does to their FFmpeg then I might be able to add it into my [statically linked FFmpeg ](https://github.com/Thefrank/ffmpeg-static-freebsd) otherwise I simply don't have the time to maintain two different forks of FFmpeg :(

**Comment by SavageCore** [comment]
I believe so!

Tried building the FFmpeg port with chromaprint but there appears to be a [circular dependency](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208877) and is now marked as broken.

I've got a separate jail going for testing so I'm more than happy to test changes.

**Comment by Thefrank** [comment]
I should have some time this weekend to look into this further and get something uploaded

**Comment by Thefrank** [comment]
@SavageCore 
My statically-linked FFmpeg 5.1.1 w/ chromaprint plus a few extra libs needed to prevent circular dependencies.
https://we.tl/t-jeTs7WAbyx

This is still missing some common items that other static builds have such as: libfreetype, fontconfig, libbluray, libvmaf

report (basically just a `cat` of FATE)
4 concerning failures: all `dnn-*`
a number of source fails due to incompatible headers
[report.txt](https://github.com/Thefrank/jellyfin-server-freebsd/files/10532300/report.txt)

Let me know how it goes or if you want a version with debug symbols.

**Comment by SavageCore** [comment]
That works great thank you!

**Comment by diamondpete** [comment]
This works to support the intro-skipper plugin 👍.

I assume that the missing common items is why my videos are being forced to transcode.
