### ISSUE TITLE
Updated Jellyfin through True Nas, now it won't start.

### ISSUE THREAD

**Issue by Lbcowman** [Thefrank/jellyfin-server-freebsd#52]
I used True NAS Core to update the plugin for Jellyfin, but now I can't access the web page. I have tried both through my local network and through my proxy manager and neither work. Everything was working fine before. True NAS says it is up and running through the plugins and jails page and I can interact with the jail through the shell but the web page will not load. All of my other jails are running just fine as normal. I have attempted to fix the issue by updating again, restarting the jail, restarting the server but nothing has worked so far. Any help is appreciated, thanks.

**Comment by Thefrank** [comment]
From inside the jail:
- does `ps aux` show it running? (there should be two processes: the daemon and the actual process)
- does `netstat` show it connected?
- does `sockstat` show it opening/listening on ports?

**Comment by Lbcowman** [comment]
> * does `ps aux` show it running? (there should be two processes: the daemon and the actual process)

![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/104144309/839d4d3a-866e-46f4-b423-b5e2f5914d11)

> * does `netstat` show it connected?

![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/104144309/4739fc86-c80c-44f4-80d0-d7ddfff0d588)

> * does `sockstat` show it opening/listening on ports?

![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/104144309/66f8e564-7870-4096-b6f3-709d7f9e7e49)

Man! I have no clue how to interpret this! However, these screenshots should help.

Thanks!!!

**Comment by Thefrank** [comment]
It is not running. `jellyfin` would show up on process list. You can try and manually start the service `service jellyfin start`

**Comment by Lbcowman** [comment]
It doesn't seem to work, and I also can't find the file it seems to be looking for.

![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/104144309/2eeeb03f-bff2-487d-a27e-24e65366b680)

![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/104144309/056449c5-28c2-4078-b776-3f061e13f645)

**Comment by Thefrank** [comment]
I guess the next question... is it even installed? `pkg info jellyfin` should return info about it or a `pkg: No package(s) matching` error if not

**Comment by Lbcowman** [comment]
Wow.... I got a no package error. I guess updating uninstalled it somehow. I guess I'll download a new version and then copy and replace all the files left? Unless you can think of a better option.

Thanks for all this help btw

**Comment by Thefrank** [comment]
`pkg install jellyfin` should work :)

**Comment by Lbcowman** [comment]
> `pkg install jellyfin` should work :)

After running this, and a restart everything is working perfectly!!! 

Do you or does this project have any way I can donate?

**Comment by Thefrank** [comment]
Glad everything is up and running now!

I currently don't accept financial donations but...
- the FreeBSD foundation could always use them: https://freebsdfoundation.org/donate/
- Jellyfin does not officially build a FreeBSD version but if you want to donate to them, they use Open Collective: https://opencollective.com/jellyfin . Maybe it will encourage them to look into official support?

and as always, contributions of code are welcome across all open source projects :)

**Comment by Kanzuke117** [comment]
I think I had the same issue, used TrueNAS Core to update jellyfin and its jail, jail goes up but no response for the web page. Stumble my way to the log files and find the process SIGTERM'd after a stream of FileNotFoundExceptions for `System.Runtime.Serialization.Formatters` and `System.IO.Pipelines`. Luck out on finding this issue that lines up, and follow the steps. No jellyfin processes running in `ps aux` or `sockstat`, and no startup script found when attempting to enable and start the service.

I run `pkg install jellyfin` and surprise, 72 packages to install. Part of that process included making a new user and group `jellyfin` instead of the `jellyfinserver` that was in use previously, and I suspected that the reason for why even though the service started and web-page went up, I get a server selector with one option that doesn't connect. So I find the [install guide](https://github.com/Thefrank/jellyfin-server-freebsd/blob/main/Installation_TrueNAS_GUI.md) and `sysrc` back to `jellyfinserver` for user and group, `service jellyfin start` now just gives me `WARNING: failed to start jellyfin`. Nothing new written to the logs in `/var/db/jellyfin/log` or `/jellyfinserver/log`. I try reinstalling with `pkg remove` and `pkg install`, delete the recreated user and group, no change. I double check `rc.conf`, and try editing the `rc.d` `jellyfin` script to manually specify the user, group, data and cache directories, no change. 

I've hesitated on trying to just reinstall the jail from scratch because I don't know where all the media metadata lives other than vaguely `/var/db`. Any advice on how to un-foobar my install or otherwise salvage what I can would be greatly appreciated

**Comment by Thefrank** [comment]
@Kanzuke117 
When jellyfin landed in the ports tree, it was given a user and group. These are different the ones I randomly assigned when I was packaging it myself. The UID/GID (User/Group ID) numbers will be different because of this. This ALSO changed the default names for: the db, the process id and the cache path

Try this:
 - REINSTALL jellyfin with: `pkg install -f jellyin`. This should force reinstall jellyfin and undo any changed files.
 - REMOVE any entries to `sysrc` that you made that changed any of the `jellyfin` or `jellyfinserver` RC vars (e.g., `sysrc -x jellyfinserver_user`). If you need a list of all non-default ones you can use `sysrc -a`
 - START jellyfin `service jellyfin start`
 Does it start with this default setup? If yes, make changes from here. If no, let me know and post if you got an error.

**Comment by Kanzuke117** [comment]
I ended up just restoring from snapshot and updating manually following the steps I found [here](https://github.com/Thefrank/jellyfin-server-freebsd/issues/49#issuecomment-1540190015) (though I don't know why they chose to cp instead of mv, the db folder is pretty heavy). Everything seems to be running smoothly now, and notably `pkg install jellyfin` only needed to add or replace about three packages instead of 72, so I have *no* idea what the automatic plugin update did. At least this was a learning experience
