### ISSUE TITLE
Run v10.9.9 into TrueNAS

### ISSUE THREAD

**Issue by DArk0711** [Thefrank/jellyfin-server-freebsd#81]
Hello. Is there a guide on how to run v10.9.9 on TrueNAS? I am not an expert at all. When installing the plugin, the server does not respond, I do not know what to do. The application does not want to work with the old version. Is it possible to build a pkg? Please help.

**Comment by Thefrank** [comment]
Which version of TrueNAS are you running? If you are running one based on FreeBSD 13.1 (e.g., TrueNAS CORE 13.0-U6.2) then you are out of luck there. Wait until TrueNAS is updated to FreeBSD 13.3 and the use the plugin. I THINK it uses the pkg version of Jellyfin now instead of trying to grab and install binaries from here.

If you ARE running TrueNAS CORE 13.3 and using the plugin then it sounds like an issue with the plugin that will need to be addressed. If you are not using the plugin the instructions `Installation_TrueNAS_GUI.md` should cover everything. If not, let me know so I can help with them. 

I do not provide a pkg as I would prefer that people do not side-load Jellyfin; ports/pkg will eventually catch up.

**Comment by DArk0711** [comment]
Thank you very much for your quick reply. I will collect all the information and reply to you soon.

**Comment by DArk0711** [comment]
Yes, I have TrueNAS-13.0-U6.1 unfortunately. I will wait for the update. I hope by that time Jellyfin will not be updated even higher. =)
